services:
  baldwinit:
    build: .
    container_name: baldwinit
    environment:
      - APP_NAME=BaldwinIT
      - APP_URL=https://baldwinit.tech
      - CONTACT_EMAIL=support@baldwinit.tech
      - TICKET_URL=https://mspguild.tech/public/modules/frontdesk/create.php
    networks:
      - infrastructure_management_net
    expose:
      - "80"

networks:
  infrastructure_management_net:
    external: true
